### ISSUE TITLE
DB error due to month having apostrophe in Sh'vat

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#10]
**Db error on temp table when a yahrzeit date falls in Sh'vat when the **Calculate job** is run as below**:
**Quick fix** take the apostrophe out of the string so Sh'vat becomes Shvat. This allows the Calculate job to run successfully although it produces on screen:
"5776-2-30: inside verify function :

2/30/5776 Test heb: 2/30/5776

5776-2-30: inside verify function :

2/30/5776 Test heb: 2/30/57761" 

**Sample Log**
Sep 10 20:26:38  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

```
[code] => -2
[message] => DB Error: syntax error
[mode] => 16
[debug_info] => INSERT INTO civicrm_fountaintribe_yahrzeits_temp ( mourner_contact_id,
  mourner_name, 
  deceased_contact_id,
  deceased_name, 
  deceased_date, d_before_sunset,
  hebrew_deceased_date, yahrzeit_date ,
  yahrzeit_hebrew_date_format_hebrew, yahrzeit_hebrew_date_format_english,
  yahrzeit_date_display, relationship_name_formatted, yahrzeit_type,
  mourner_observance_preference, plaque_location,
  yahrzeit_erev_shabbat_before, yahrzeit_shabbat_morning_before,
  yahrzeit_erev_shabbat_after , yahrzeit_shabbat_morning_after,
  yahrzeit_date_morning, yahrzeit_relationship_id
  )
        VALUES(2149, 'XXXX' , 2715,
        'XXXX', 
         '1945-2-9' , 'Yes',
        '26 Sh'vat 5705' , '2017-02-21',
        'כו שבט התשעז', '26 Sh\'vat 5777',
        '21 February 2017 starting at sunset ', 'husband', '0',
        '0', 'Unknown or No Plaque',
        '2017-02-17', '2017-02-18', '2017-02-24', '2017-02-25',
        '2017-02-22', '20'  ) [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'vat 5705' , '2017-02-21',
        'כו שבט התשעז', '26 Sh\'vat 5777',
        '21' at line 17]
```

**Comment by sgladstone** [comment]
This has been fixed in version 3.0 (https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/tree/3.0) 

You should disable and re-enable the extension (if this does not happen during the upgrade).

**Comment by gzh1960** [comment]
Thank you Sarah, have tested and it works really well. Well done again! 

We may need to adjust our policy on when we recite memorial prayers as we have used a formula over the years of Wed through to the following Tues as the period for reciting the current yahrzeits on the shabbat between these days. However,I think it is only a custom (and in fact, it was actually due to a spreadsheet formula that was used for years to calculate the related shabbat) and therefore to make things easier we may make policy decision to use the shabbat before the Yahrzeit and that way we can use this column you have provided.
Thanks again for this modification. BTW, the hebrew font is coming out now in the PDF too!

**Comment by gzh1960** [comment]
Thank you. Tested and behaving now !

**Comment by gzh1960** [comment]
Sarah, one thing still, when I run the Calculate job manually the screen fills up with messages like below:
"5776-2-30: inside verify function :

2/30/5776 Test heb: 2/30/5776

5776-2-30: inside verify function :

2/30/5776 Test heb: 2/30/57761" 
The job runs successfully.
I assume there must be some monitoring/debugging code somewhere logging the dates,can you check this please?

**Comment by sgladstone** [comment]
The debug message has been removed in the latest version:  3.0.4

**Comment by gzh1960** [comment]
All good now thank you!
