### ISSUE TITLE
Calculate job will not run using cron

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#11]
Calculate job will not run using cron. Works fine when run manually.

https://wiki.civicrm.org/confluence/display/CRMDOC/Managing+Scheduled+Jobs#ManagingScheduledJobs-URLmethod

states "Specific Job via URL works only for API entity = job

Note that you can execute API actions only from the API entity "job"; this is hard-coded into cron.php.  So you can't call any of the built in API functions (other than those under entity "job") using cron.php, but you also can't create a new API action  So for instance, if you create new API entity called "myapi" with API action "my action" then you would be able to call that action via the Scheduled Jobs page but you will not be able to call it via cron.php. "

A possible workaround for this problem is here: http://forum.civicrm.org/index.php/topic,28215.0.html
I tried this but still got the following error:
Fatal error</b>:  Call to a member function saveLastRun() on null in <b>/home/cremorne/www/www/prodwp/wp-content/plugins/civicrm/civicrm/CRM/Core/JobManager.php</b> on line <b>122</b>

Any thoughts here on this one please?

**Comment by sgladstone** [comment]
Per the page: https://wiki.civicrm.org/confluence/display/CRMDOC/Managing+Scheduled+Jobs

> Run ALL Scheduled Jobs via URL
> 
>  Calling cron.php as shown below will run ALL scheduled jobs that are Enabled and are due to run based on last run and run frequency:

See https://wiki.civicrm.org/confluence/display/CRMDOC/Managing+Scheduled+Jobs#ManagingScheduledJobs-RunALLScheduledJobsviaURL
