### ISSUE TITLE
For yahrzeit custom search, add filter for Hebrew month, Hebrew year

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#13]
Multiple (same) records returned when yahrzeit date range used.

**Selection criteria:** 
Group=Active Yahrzeits
Date From 1/9/2016 
...Through 31/08/2017

Returns multiple records for the same mourner/deceased combination due to hebrew date falling on different English months in different years.

[Mutiple same records issue.pdf](https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/files/468645/Mutiple.same.records.issue.pdf)

Could a search perhaps by hebrew date be done so the multiple record situation does not occur?

FYI:_Workaround_ to produce current year's yahrzeit list for High Holidays is on export of the data based on the search criteria above is to manually remove the multiple records in a spreadsheet and then print the list.

**Comment by sgladstone** [comment]
The nature of filtering by English calendar dates produces this situation.   The custom search enhancement of allowing a filter on the Hebrew dates such as filtering on 5778  will produce a list of yahrzeits where each deceased is only listed once per mourner.

**Comment by sgladstone** [comment]
There is now a filter on the Hebrew year. So if you filter on the year 5777 you will get at most 1 yahrzeit per deceased person.

**Comment by sgladstone** [comment]
Also there is a filter on the Hebrew month.
