### ISSUE TITLE
Mourner Gender criteria not returning results when the Yahrzeit Search is run. 

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#14]
Mourner Gender criteria not returning results when the Yahrzeit Search is run. 

**Selection criteria:**
Group=Active Yahrzeits
Mourner Gender Male

(tried Female also and same result)
Returns no records. 

Setup includes mourners with gender set to Male or Female.

**Comment by sgladstone** [comment]
I was able to reproduce this, and this has been fixed in version 3.0.5

**Comment by gzh1960** [comment]
Thank you so much for fixing this...it makes things much easier now!
