### ISSUE TITLE
Ability to filter Yahrzeit Search based on member status

### ISSUE THREAD

**Issue by spt83** [sgladstone/com.fountaintribe.hebrewcalendarhelper#15]
We would like to exclude expired/cancelled members from the Yahrzeit search. Thanks

**Comment by sgladstone** [comment]
This is already in place when you choose any of the existing membership filters on the yahrzeit search.  You can control which membership statuses represent "active members" at "Administer ... CiviMember ... Membership Status Rules".    See screen prints below: 

![image](https://cloud.githubusercontent.com/assets/2640984/21750558/d377f56e-d583-11e6-87f3-c556d0d474ed.png)

![image](https://cloud.githubusercontent.com/assets/2640984/21750581/5774d42c-d584-11e6-84b9-64082b6ac20b.png)
