### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by yosefromano** [sgladstone/com.fountaintribe.hebrewcalendarhelper#16]
Hi Sarah, 
I am trying to automate the Yahrtzeit reminder and I forgot how to setup the scheduled job. 
At the bottom of this page of the wiki: https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/wiki/Automated--reminders

5- Make sure that scheduled job is enabled and matches the screen print below: (use the smart group and template from steps 1 and 2 above) 

There is no screen print below. Can you please add it? 

Thanks

**Comment by yosefromano** [comment]
I think all that is needed is
group=
message_template=

In the send2each cron job

**Comment by sgladstone** [comment]
screen print is available now
