### ISSUE TITLE
Earliest Possible Bat Mitzvah Date calculating at 13 years old rather than 12

### ISSUE THREAD

**Issue by spt83** [sgladstone/com.fountaintribe.hebrewcalendarhelper#17]
Just noticed that the calculation appears to be incorrect. 
Here the example i have noticed it for
Contact gender: Female
Date of birth: 19th January 2006  
Hebrew date of birth: 19 Tevet 5766 
Next Hebrew Birthday: January 5, 2018
Earliest Possible Bar/Bat Mitzvah Date (Starts at sunset on this date): December 26, 2018

Therefore when i Calculate the Hebrew bat mitzvah date back i get 19 Tevet 5779 so 13 years old.
Is there something i have configured incorrectly or is this field calculated as 13 years for both males and females

**Comment by sgladstone** [comment]
Earliest Bar/Bat Mitzvah dates are calculated in an egalitarian way. It calculates the date when the person turns 13 years old according to the Hebrew calendar.

**Comment by sgladstone** [comment]
This is now configurable.  See description of this enhancement at: https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/issues/27
