### ISSUE TITLE
Custom Search not displaying selected field values like Mourner's Name

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#2]
Custom Search not displaying selected field values like Mourner's Name.
V2.7 installed in CiviCRM 4.6.9.
Have setup a  'Yahrzeit observed by' relationship between mourner and deceased and set yahrzeit preference also. Tried both values but no change when Custom Search run.

Result of search is the Mourner's name,Deceased Hebrew Name, Relationship to Mourner and Mourner details (far right of screen) are not displayed.

**Comment by gzh1960** [comment]
Custom Search criteria.
If I choose 'Only include Individuals with living mourners' for a date range of 1/11/2016 to 1/12/2016 no results are returned.
If I choose 'Include any record (living...)... with same date range then I get results displayed.

**Comment by gzh1960** [comment]
Added screenshot of Custom search criteria to bottom of document.
[Upcoming Yahrzeit Search Results.pdf](https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/files/429211/Upcoming.Yahrzeit.Search.Results.pdf)

**Comment by sgladstone** [comment]
Can you run the SQL query "select \* from civicrm_relationship_type " and share the results here?

BTW: I created a version 2.8, which I tested more with your date format, and that fixed the issue with the my scheduled job.

**Comment by gzh1960** [comment]
[devwp2_DumpofRelationTypes.xlsx](https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/files/429255/devwp2_DumpofRelationTypes.xlsx)
I see I have duplicate 'yahrzeit observed by..' types maybe issue?
I feel we are very close to having this work.

**Comment by sgladstone** [comment]
Please delete the SQL record:  
![image](https://cloud.githubusercontent.com/assets/2640984/17842536/eaa0b4ce-67f1-11e6-996b-6dd63f51c2ce.png)

Are you using that relationship type anywhere?  It was not created by my extension.  Did you create it by hand?

**Comment by gzh1960** [comment]
Duplicate record removed. YEs I had setup this record to record Yahrzeits info manually. Reran job and then custom search with no luck, i.e. as displayed in previous uploaded docs.

**Comment by sgladstone** [comment]
In your CiviCRM backoffice, look at the "relationships" tabs of one of your deceased contacts. Verify there is a yahrzeit relationship using the extension-created relationship for yahrzeits.

**Comment by sgladstone** [comment]
How were you tracking Hebrew dates in CiviCRM, before this extension?

**Comment by gzh1960** [comment]
tracking and calculating dates manually

**Comment by sgladstone** [comment]
I am on Skype, that might be faster to figure this out. What is your Skype name?

**Comment by gzh1960** [comment]
hymanfam

**Comment by gzh1960** [comment]
Installed V2.9 no issues (will try in a vanilla copy in time). Ran SQL update script to change the existing relationship type to the new one and the Custom Search now displays the missing column data.
