### ISSUE TITLE
Various Shabbat Parashat values are empty

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#20]
Hi Sarah,
 Just started the monthly letter production and found that the various Shabbat Parashat values are empty. See the attachment for an example. When I export the data to perform a form letter the shabbat Parashat values are empty too.

![yahrzeit-shabbat dates empty](https://user-images.githubusercontent.com/6695874/44304544-e4e3da00-a3a1-11e8-8fc7-97847c124880.PNG)

![yahrzeit hebrew calendar helper version no used](https://user-images.githubusercontent.com/6695874/44304556-54f26000-a3a2-11e8-8f87-9f5a1e8fcc69.PNG)

Help please.
Regards
Garry

**Comment by gzh1960** [comment]
fyi php version is 7.1, I also reverted back to 5.6 reran Calculate but it is no different. Now back to 7.1 again.

**Comment by sgladstone** [comment]
What has changed on your system since this was working?  Also, What is in the MySQL  yahrzeit table for this?

**Comment by gzh1960** [comment]
Sarah,
1. Only thing changed to my knowledge was upgrading the Hebrew Calendar Helper after the last issue #19 'Fatal error after changing PHP from Version 5.6 to 7.1'.
2. civicrm_fountaintribe_yahrzeits_temp is showing empty values for the parashat columns.
regards
Garry

**Comment by gzh1960** [comment]
Can confirm that the call to Hebcal is returning the correct data. Following URL I believe would be constructed and it works.

http://www.hebcal.com/hebcal/?v=1&cfg=json&maj=on&min=on&lg=s&i=off&mod=on&nx=on&year=2018&month=09&ss=on&mf=on&geo=none&c=on&m=50&s=on

Straight after the Hebcal call in the code it then tries to update the yahrzeit table and I can only think it is failing here for some reason or somehow returning null or an empty value without failing which might be more likely. Could you have a look in this area perhaps please?

 I can see that the yahrzeit_shabbat_morning_before and yahrzeit_shabbat_morning_after contain correct date values e.g. 2018-09-08 00:00:00

Any other thoughts or things you would like me to review/check?
Regards
Garry

**Comment by sgladstone** [comment]
Try https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/releases/tag/3.3.0

**Comment by sgladstone** [comment]
The Hebcal.com site is now redirecting all http:// requests to https://    I updated the extension to use https:// when connecting to hebcal.com. (otherwise the redirect breaks things)

**Comment by gzh1960** [comment]
Installed in dev and tested OK and now prod with success. Thank you so much Sarah. We make a good team. My php is improving although slowly!

**Comment by sgladstone** [comment]
FYI: I also reported this issue to the hebcal.com people: https://github.com/hebcal/dotcom/issues/32
