### ISSUE TITLE
Date icons for user selection missing from Yahrzeit custom search page

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#21]
Date icons for user selection missing from Yahrzeit custom search page.

[CiviCRM date icons missing from page.docx](https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/files/3088227/CiviCRM.date.icons.missing.from.page.docx)

Have upgraded development systems recently as follows:
mySQL 5.7.23
PHP 7.1
CiviCRM 5.12.0

**Comment by gzh1960** [comment]
Sarah,
 Any chance you can investigate this one as it is stopping us from upgrading to a later version of CiviCRM as the yahrzeit search screen becomes less friendly for the user.

Thanks
Garry

**Comment by sgladstone** [comment]
I will check on this within a week

**Comment by sgladstone** [comment]
Can you try the release at https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/releases/tag/3.4

**Comment by sgladstone** [comment]
Can you try the release at:
https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/releases/tag/4.0

**Comment by gzh1960** [comment]
Sarah,
 Thanks for this fix, I downloaded 4.0 and unzipped it to my custom extensions folder, then refreshed Civi Extensions but it just does not want to see 4.0. I cleared cache and retried no luck. I have disabled and also uninstalled V3.3.0 and still no sign of 4.0. Any thoughts please?
Thanks Garry

**Comment by sgladstone** [comment]
Try this link instead:
https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/releases/tag/4.0.0

(the previous git tag "4.0" did not match the version info inside "info.xml" file)

**Comment by gzh1960** [comment]
Still no luck. Refreshed in CiviCRM but nothing new like 4.0.0 showed up. Disabled and refereshed nothing. Uninstalled and refreshed nothing. Hmm..any ideas?

**Comment by gzh1960** [comment]
Foget my previous comment. I had to uninstall 3.3.0 and rename the 3.3.0 folder on the host and then refresh in Civicrm and 4.0.0 came up.

Getting error when I run the custom search as follows:
where: contact_deceased.is_deleted <> 1 AND ( contact_a.id is null OR contact_a.is_deleted <> 1 ) AND yahrzeit_shabbat_morning_after >= 20190601000000 AND yahrzeit_shabbat_morning_after <= 20190630000000 AND ( (groups.group_id IN (61) AND groups.status = 'Added') OR ( groupcache.group_id IN (61) ) ) AND ( contact_a.contact_type IN ( 'Household', 'Individual') AND contact_a.is_deceased <> 1 ) AND contact_a.gender_id = 2 AND (yahrzeit_type = mourner_observance_preference)


where: contact_deceased.is_deleted <> 1 AND ( contact_a.id is null OR contact_a.is_deleted <> 1 ) AND yahrzeit_shabbat_morning_after >= 20190601000000 AND yahrzeit_shabbat_morning_after <= 20190630000000 AND ( (groups.group_id IN (61) AND groups.status = 'Added') OR ( groupcache.group_id IN (61) ) ) AND ( contact_a.contact_type IN ( 'Household', 'Individual') AND contact_a.is_deceased <> 1 ) AND contact_a.gender_id = 2 AND (yahrzeit_type = mourner_observance_preference)


where: contact_deceased.is_deleted <> 1 AND ( contact_a.id is null OR contact_a.is_deleted <> 1 ) AND yahrzeit_shabbat_morning_after >= 20190601000000 AND yahrzeit_shabbat_morning_after <= 20190630000000 AND ( (groups.group_id IN (61) AND groups.status = 'Added') OR ( groupcache.group_id IN (61) ) ) AND ( contact_a.contact_type IN ( 'Household', 'Individual') AND contact_a.is_deceased <> 1 ) AND contact_a.gender_id = 2 AND (yahrzeit_type = mourner_observance_preference)


Warning: Cannot modify header information - headers already sent by (output started at /home/cremorne/www/www/devwp2/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php:523) in /home/cremorne/www/www/devwp2/wp-content/plugins/civicrm/civicrm/CRM/Utils/System/Base.php on line 926

**Comment by gzh1960** [comment]
parameters used below:

![image](https://user-images.githubusercontent.com/6695874/58557020-b3693a80-8260-11e9-910f-edf220593963.png)

**Comment by sgladstone** [comment]
I am running this extension on the following stack:
CiviCRM 5.13.4
Drupal 7.51
PHP 7.2.11
MySQL 5.6.40
Apache 2.4.34

Yet I am not able to reproduce your issue.  I also checked the source code for my extension, and verified there are no "print" or "print_r" statements.      Can you try clearing the CiviCRM cache? 

Delete all files in your templates_c directory
 `<wordpress_root>/<content-dir>/uploads/civicrm/templates_c`

**Comment by gzh1960** [comment]
Cleared cache and templates_c folder. Retried and no luck with same error. Reran Calculate job too and retried.

I noticed that this 4.0.0 extension changes the user filtering criteria compared to what it used by like. Is there anything else that I might need going from 3.3.0 to 4.0.0? Why was it changed?

**Comment by sgladstone** [comment]
I added the choice "how to choose dates" so that I could then show just the relevant choices for selecting the date range. I thought this improved the layout, as before it was confusing for a new user.

**Comment by gzh1960** [comment]
Sarah,
FYI, I have upgraded CiviCRM to 5.16.3 successfully and used Hebrewcalendarhelper version 4.0.0. When I run the specific dates option I still get the error shown above re Warning: Cannot modify header information - headers already sent by (output started at /home/cremorne/www/www/devwp2/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php:527.

I have commented out this line 527 in Error.php (see below)and rerun the search and it works with no issue. Not sure why this is happening though. The new layout you have supplied is fine and works well other than this issue.

    if (
      $log &&
      (!$checkPermission || CRM_Core_Permission::check('view debug output'))
    ) {
**/*      echo $out;*/**
    }

Regards
Garry

**Comment by sgladstone** [comment]
Garry - I found the issue and corrected it.   Please try version 4.0.2
Link to new version:
https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/releases/tag/4.0.2

FYI: I eliminated one line of code that I had used for debugging.  (in other words, debugging was the bug) The line I removed: 
`CRM_Core_Error::debug( "<br>where: ".$tmp_rtn , "");`

This release also should address the tokens being blank when used to send emails.

**Comment by gzh1960** [comment]
Thank Sarah,
 Have installed 4.0.2, backed out my previous fix in error.php and tested with success. Think we have a winner here! (Funny how the debugging can cause the bug! Seen it a few times in my day too!)
Regards
Garry
