### ISSUE TITLE
Yahrzeit Search having issue `SELECT list is not in GROUP BY clause and contains nonaggregated column 'db_name.contact_b.mourner_name'`

### ISSUE THREAD

**Issue by ddhuri** [sgladstone/com.fountaintribe.hebrewcalendarhelper#24]
After searching data with Yahrzeit Search it fails and shows the error like `SELECT list is not in GROUP BY clause and contains nonaggregated column 'db_name.contact_b.mourner_name'`

I have used versions as follows :
CiviCRM 5.9
HEBREW CALENDAR 4.0.0 
Mysql 5.7.24

**Comment by ddhuri** [comment]
This issue is fixed with disabling ONLY_FULL_GROUP_BY option from sql_mode.
Is there any other solution which will fix this?

**Comment by sgladstone** [comment]
Please try the version of the extension at: https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/releases/tag/4.0.3

(This is a dev branch, do not use on a production site.)

**Comment by sgladstone** [comment]
This has been fixed. The fix is now part of the latest release 4.0.4:
https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/releases/latest

Please be sure to disable, then re-enable the extension after the upgrade.

**Comment by gzh1960** [comment]
Sarah,
 Have installed 4.0.4 successfully and tested yahrzeit seach facility is working as expected.
Regards
Garry

**Comment by sgladstone** [comment]
@ddhuri   Are you have a chance to verify version 4.0.4 is working as expected?

**Comment by ddhuri** [comment]
Thanks, @sgladstone Have tested this with latest release 4.0.4 and it's working absolutely fine without disabling ONLY_FULL_GROUP_BY option from sql_mode
