### ISSUE TITLE
enhancement request: add related shabbat parsha as a token

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#3]
This is an enhancement request to add related shabbat parsha as a token.
If the yahrzeits dates calculated co-incide with say parsha Eikev then it would be great to have this related shabbat parsha available as a token for either the email or pdf actions from the results of the yahrzeits custom search.

**Comment by gzh1960** [comment]
This would be the priority out of the remaining enhancements. Could this value be added to the existing yahrzeit results page and underlying table.

**Comment by sgladstone** [comment]
The parashat info for shabbat before and after the yahrzeit is now part of the Yahrzeit custom search.  Make sure you have upgraded this extension to version 3.0.1 or higher to see this new feature in the custom search and the new tokens.

**Comment by sgladstone** [comment]
The documentation on how to use the new tokens is at: https://github.com/sgladstone/com.fountaintribe.hebrewcalendarhelper/wiki

**Comment by gzh1960** [comment]
Thank you Sarah, have tested and it works really well. Well done again! 

We may need to adjust our policy on when we recite memorial prayers as we have used a formula over the years of Wed through to the following Tues as the period for reciting the current yahrzeits on the shabbat between these days. However,I think it is only a custom (and in fact, it was actually due to a spreadsheet formula that was used for years to calculate the related shabbat) and therefore to make things easier we may make policy decision to use the shabbat before the Yahrzeit and that way we can use this column you have provided.
Thanks again for this modification. BTW, the hebrew font is coming out now in the PDF too!
