### ISSUE TITLE
enhancement request: add tribe as a token

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#6]
enhancement request: add tribe as a token.
This data could be selected from a list of values namely, Cohen, Levi or Israelite  (default value israelite).
To be stored in religious region on contact record

**Comment by sgladstone** [comment]
I am assuming the token would be needed for a living contact?

**Comment by gzh1960** [comment]
Yes definitely for living but can also be used for deceased for yahrzeits eg. baruch ben david **hacohen**.

**Comment by sgladstone** [comment]
This is now part of version 2.10

**Comment by sgladstone** [comment]
I intentionally did not make any tribe a default, as then 'Israelite' would get filled in for contacts where does not make sense. ( ie vendors tracked in CiviCRM, non-Jewish donors, etc)
