### ISSUE TITLE
enhancement request: add seating info

### ISSUE THREAD

**Issue by gzh1960** [sgladstone/com.fountaintribe.hebrewcalendarhelper#7]
enhancement request: add seating info including seat number, available if it is free or vacant or not available as some contacts pay for it during the year, storage box for men especially to hold tallit,  prayer books, section of shul for different seats e.g. fixed seats, removable seats, cloth, padded seats, upstairs, downstairs etc and seat comments which is a free text entry area to record comments related to the seat.
I actually set this up on the contact record for manual entry and called the region Seating Information but never implemented it. 
If this data was entered then the next step would be to produce a seating plan or layout if possible and or a listing of seat numbers with the assigned contact's name for printing to place on the foyer wall for High Holidays. Need to sort this by name and / or seat number sequence.

**Comment by sgladstone** [comment]
I am not sure how assigned/reserved seating relates to this extension. I think this would make more sense to add to CiviBooking: https://civicrm.org/extensions/civibooking

**Comment by sgladstone** [comment]
CiviBooking already covers virtually all of what you are describing here.

**Comment by gzh1960** [comment]
OK thanks will take another look in time at CiviBooking.
